### ISSUE TITLE
No hay suficiente picardía (era: Hola)

### ISSUE THREAD

**Issue by capellanistico** [noquierouser/tavocles#2]
Capo, una sola cosa no más quería decirte, me agradó mucho tu post, en serio, es de lo más sensacional que he visto por el momento, es una obra de arte, sin exagerar, es algo que a simple vista podría haber sido hecho por el mismísimo Da Vinci, la genialidad que tiene se puede notar desde kilómetros de distancia, ni siquiera la peor de las malas lenguas podría decir que no nos encontramos ante una majestuosidad vista una sola vez cada mil años. No he visto en todos mis años de vida algo de esta magnitud, te provoca una sensación indescriptible, una alegría inmensa a pesar de no haber hecho acción alguna, una sentimiento raro de encontrar pero fantástico, algo así como lo que se siente una brisa en un caluroso verano, ver la alegría de un niño al abrir sus regalos de navidad, o simplemente estar con esa persona que tanto queremos. No hagas caso a las malas lenguas que critican sin cesar a cualquiera que no cumpla con absolutamente todas sus expectativas, sólo créeme a mi y a todos aquellos seres que consideran y admiran a tan grandiosa obra de arte. Siempre va a haber personas que te van a decir que lo que hiciste no tiene valor, pero el secreto está en ignorarlas, esas personas darían lo que fuera por haber creado algo tan magnífico como lo que estamos viendo. Así como Dios en su infinita sabiduría creo la humanidad, o así como un hombre enamorado crea un poema para expresar sus más profundos sentimientos, o como un pintor crea una obra de arte de algún tiempo que ni siquiera él conoce, así es como fue creado este post, de la misma forma. Puede parecer que estoy exagerando, repito, pero no es así, ni de cerca, exageraría si dijese que no me encuentro ante una creación admirable, increíble, de una belleza de proporciones bíblicas. De hecho estoy tan encantado con semejante aporte que decidí escribir un poema al respecto, se titula "mis ojos te lo agradecen", aquí va: "Mis ojos te lo agradecen, ya que han sido acariciados, mis sentimientos te alaban, ya que han sido despertador, mi corazón te idolatra, porque lo has hecho bailar y mi ser te dice gracias, por tan delicioso manjar, estaré esperando nuevamente, que me compartas tu alegría, aún en medio de la noche, o en el más radiante día, solo sigue creando, creando hasta que las pesen, así te diré nuevamente, mis ojos te lo agradecen". Espero que hayas disfrutado mi poema tanto como yo disfruté escribiéndolo, te diría que lo disfrutes como yo disfruté tu post, pero no creo que haya situación alguna en el mundo que se asemeje a tanta dicha. Para terminar siendo breve, te quería agradecer de corazón, uno en esta vida se encuentra con situaciones que lo ponen de malas, piensa que no va a encontrar nada bueno en estos días y de repente se encuentra con algo así, es difícil decidir donde uno va a dejar sus puntos, y de hecho ya cansa denunciar la mayoría de los post que ve, siendo que muchos son creados por trolls y personas con ganas de molestar, nada que ver con lo que estamos observando, aquí uno piensa todo lo contrario, simplemente no lo ve y se dice a si mismo "no debe haber lugar en esta tierra, ni en el mundo ni en el inframundo, ni en otros planetas, galaxias o universos, donde sea mejor dejar mis puntos, he encontrado la verdadera Atlantida, aunque no sea un lugar físico, su simple belleza es suficiente para no titubear en hacer dicha comparación". A veces me pregunto cuanta destreza o cuanta habilidad hace falta tener para poder realizar una creación de esta índole, a veces me comparo con los creadores de hermosuras como esta y pienso que no soy si quiera un simple ser humano, al lado de dicho creadores me siento como una hormiga frente a un imponente elefante, como un peón al lado de una reina, como un niño frente a un super héroe de esas historietas que tanto gustan leer.

**Comment by noquierouser** [comment]
Esperamos mantener esa calidad.
